version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:659266464590:task-definition/aws-hello-world-rest-api:10"
        LoadBalancerInfo:
          ContainerName: "hello-world-rest-api"
          ContainerPort: "80"
        PlatformVersion: "LATEST"